"""Generation ORM model.

Represents a single LLM-generated content piece.
"""

from __future__ import annotations

from datetime import datetime
from uuid import uuid4

from sqlalchemy import DateTime, ForeignKey, Integer, String, Text, func
from sqlalchemy.dialects.postgresql import JSON
from sqlalchemy.orm import Mapped, mapped_column, relationship

from src.database import Base


class Generation(Base):
    """A content piece generated by an LLM."""

    __tablename__ = "generations"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=lambda: str(uuid4()))
    brand_voice_id: Mapped[str | None] = mapped_column(
        String(36), ForeignKey("brand_voices.id"), nullable=True
    )
    content_type: Mapped[str] = mapped_column(String(20), nullable=False)  # blog, social, email
    topic: Mapped[str] = mapped_column(Text, nullable=False)
    parameters: Mapped[dict] = mapped_column(JSON, default=dict)
    generated_text: Mapped[str] = mapped_column(Text, default="")
    compliance_scores: Mapped[dict] = mapped_column(JSON, default=dict)
    model_used: Mapped[str] = mapped_column(String(100), default="gpt-4o")
    tokens_used: Mapped[int] = mapped_column(Integer, default=0)
    latency_ms: Mapped[int] = mapped_column(Integer, default=0)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    brand_voice: Mapped[BrandVoice | None] = relationship(lazy="selectin")


# Avoid circular import
from src.models.brand_voice import BrandVoice  # noqa: E402
